#!/usr/bin/env python3
"""Build the installed skill configuration from the canonical project registry."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


SKILL_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_PROJECTS = REPOSITORY_ROOT / "config" / "projects.toml"
DEFAULT_OUTPUT = SKILL_ROOT / "config.toml"

HEADER = """# Generated by scripts/sync_config.py from the canonical repository project registry.
# Do not edit this packaged snapshot directly; synchronize and reinstall the skill.

[task_creation]
task_kinds = ["implementation", "research", "experiment"]
default_stop_condition = "Finish the requested work and validation, then stop ready for review. Do not commit, push, or open a PR unless another workflow explicitly requests it."

[task_creation.primary_categories.feature]
linear_label = "Feature"
change_type = "feat"

[task_creation.primary_categories.bug]
linear_label = "Bug"
change_type = "fix"

[task_creation.primary_categories.chore]
linear_label = "Chore"
change_type = "chore"

[task_creation.primary_categories.docs]
linear_label = "Docs"
change_type = "docs"

[task_creation.primary_categories.refactor]
linear_label = "Refactor"
change_type = "refactor"

[task_creation.research_modifier]
linear_label = "Research"

"""


def render(projects_path: Path) -> str:
    try:
        projects = projects_path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise ValueError(f"cannot read canonical project registry: {projects_path}") from error
    if not projects.strip():
        raise ValueError("canonical project registry is empty")
    return HEADER + projects.strip() + "\n"


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description="Synchronize the packaged task-creation config")
    result.add_argument("--projects", type=Path, default=DEFAULT_PROJECTS)
    result.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    result.add_argument("--check", action="store_true")
    return result


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        expected = render(args.projects)
        if args.check:
            try:
                current = args.output.read_text(encoding="utf-8")
            except (OSError, UnicodeError) as error:
                raise ValueError(f"cannot read packaged config: {args.output}") from error
            if current != expected:
                print(
                    "Packaged skill config is out of date; run scripts/sync_config.py and reinstall the skill",
                    file=sys.stderr,
                )
                return 1
            return 0
        args.output.write_text(expected, encoding="utf-8")
        return 0
    except ValueError as error:
        print(f"Cannot synchronize skill config: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
