#!/usr/bin/env python3
"""Build the installed skill configuration from the canonical project registry."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
import subprocess
import tempfile
import tomllib


SKILL_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_PROJECTS = REPOSITORY_ROOT / "config" / "projects.example.toml"
PRIVATE_PROJECTS = REPOSITORY_ROOT / "config" / "projects.toml"
DEFAULT_OUTPUT = SKILL_ROOT / "config.example.toml"

HEADER = """# Generated by scripts/sync_config.py.
# Refresh from the appropriate example or private registry; do not edit mappings here.

[task_creation]
task_kinds = ["implementation", "research", "experiment"]
default_stop_condition = "Finish the requested work and relevant focused validation, honoring explicit local/per-pass requirements. Report actual commands/results and outstanding checks honestly, including pending merge-time validation for CI or human verification; do not assume an external gate exists. Then stop ready for independent review. Do not commit, push, or open a PR unless another workflow explicitly requests it."

[task_creation.primary_categories.feature]
linear_label = "Feature"
change_type = "feat"

[task_creation.primary_categories.bug]
linear_label = "Bug"
change_type = "fix"

[task_creation.primary_categories.chore]
linear_label = "Chore"
change_type = "chore"

[task_creation.primary_categories.docs]
linear_label = "Docs"
change_type = "docs"

[task_creation.primary_categories.refactor]
linear_label = "Refactor"
change_type = "refactor"

[task_creation.research_modifier]
linear_label = "Research"

"""


def render(projects_path: Path, *, private: bool = False) -> str:
    try:
        projects = projects_path.read_text(encoding="utf-8")
        data = tomllib.loads(projects)
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
        raise ValueError(f"cannot read project registry: {projects_path}") from error
    allowed = {"projects"} if private else {"projects", "example_only"}
    if set(data) != allowed or not private and data["example_only"] is not True:
        raise ValueError("public config requires marked examples; private config requires an unmarked runtime registry")
    entries = data["projects"]
    if not isinstance(entries, dict) or not entries:
        raise ValueError("registry requires project mappings")
    names, repos = set(), set()
    for entry in entries.values():
        if not isinstance(entry, dict) or set(entry) - {
                "linear_project", "linear_team", "repo_name", "base_branch", "replace_workflow_labels"}:
            raise ValueError("unsupported project mapping fields")
        for key in ("linear_project", "repo_name", "base_branch"):
            if not isinstance(entry.get(key), str) or not entry[key].strip():
                raise ValueError(f"project mapping requires {key}")
        if entry["linear_project"].strip() in names or entry["repo_name"].strip() in repos:
            raise ValueError("ambiguous project mappings")
        names.add(entry["linear_project"].strip())
        repos.add(entry["repo_name"].strip())
    # Serialize only parsed mapping values. Comments in a private registry may
    # contain personal notes and must never be copied into installed artifacts.
    lines = [] if private else ["example_only = true", ""]
    lines.append(HEADER.rstrip())
    for key, entry in entries.items():
        lines.extend(["", f"[projects.{json.dumps(key, ensure_ascii=False)}]"])
        for field, value in entry.items():
            if field == "replace_workflow_labels":
                if type(value) is not bool:
                    raise ValueError("replace_workflow_labels must be boolean")
            elif not isinstance(value, str) or not value.strip():
                raise ValueError("project mapping fields must be nonempty text")
            lines.append(f"{field} = {json.dumps(value, ensure_ascii=False)}")
    return "\n".join(lines) + "\n"


def private_output(path: Path) -> Path:
    output = path.expanduser().absolute()
    if (output.name != "config.local.toml" or output.resolve() != output
            or output.exists() and (not output.is_file() or output.stat().st_nlink != 1)):
        raise ValueError("private output must be a regular config.local.toml outside any Git checkout")
    parent = output.parent
    while not parent.exists():
        parent = parent.parent
    if output.resolve().is_relative_to(REPOSITORY_ROOT):
        raise ValueError("private installed mappings must stay outside the source repository")
    probe = subprocess.run(["git", "-C", str(parent), "rev-parse", "--show-toplevel"],
                           capture_output=True, text=True)
    if probe.returncode == 0:
        raise ValueError("private installed mappings must stay outside Git checkouts")
    return output


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description="Generate public examples or explicitly install private task mappings")
    result.add_argument("--projects", type=Path, help="registry source (private mode only)")
    result.add_argument("--private", action="store_true", help="install private runtime mappings outside Git")
    result.add_argument("--output", type=Path, help="explicit installed config.local.toml path (required with --private)")
    result.add_argument("--check", action="store_true")
    return result


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        if args.private:
            if args.output is None:
                raise ValueError("--private requires an explicit --output installed config.local.toml")
            output = private_output(args.output)
            projects = args.projects or PRIVATE_PROJECTS
        else:
            if args.projects is not None or args.output is not None:
                raise ValueError("custom registry/output requires --private; public synchronization uses only examples")
            output, projects = DEFAULT_OUTPUT, DEFAULT_PROJECTS
        expected = render(projects, private=args.private)
        if args.check:
            try:
                current = output.read_text(encoding="utf-8")
            except (OSError, UnicodeError) as error:
                raise ValueError(f"cannot read generated config: {output}") from error
            if current != expected:
                print(
                    "Packaged skill config is out of date; run scripts/sync_config.py and reinstall the skill",
                    file=sys.stderr,
                )
                return 1
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        if args.private:
            # Create privately from the first byte and replace atomically.
            temporary = None
            try:
                with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=output.parent,
                                                 prefix=".config-", delete=False) as source:
                    temporary = Path(source.name)
                    source.write(expected)
                os.replace(temporary, output)
            finally:
                if temporary is not None:
                    temporary.unlink(missing_ok=True)
        else:
            output.write_text(expected, encoding="utf-8")
        return 0
    except (ValueError, OSError) as error:
        print(f"Cannot synchronize skill config: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
